Farewell/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'farewell/',include('party.urls', namespace='party')),
]

party/urls.py
from django.urls import path,include

from . import views

app_name='party'

urlpatterns = [

    path(r'home/',views.index,name='index'),
    path(r'gotcha/',views.gotcha,name='gotcha'),
    path(r'oqp/',views.oqp,name='oqp'),
    path(r'wishingwell/',views.wishingwell,name='ww'),
    path(r'sorry/',views.sorry,name='sorry'),
]

party/models.py
from django.db import models

# Create your models here.


class Feedback(models.Model):
    name=models.CharField(max_length=20)
    feedback=models.TextField(max_length=200)


    def __str__(self):
        return str(self.name) + " 's feedback"


class Gotcha(models.Model):
    sl_no=models.AutoField(primary_key=True)
    secret=models.TextField(max_length=500)

    def __str__(self):
        return "secret number - "+str(self.sl_no)


class Oqp(models.Model):
    recipient=models.CharField(max_length=20)
    question=models.TextField(max_length=500)

    def __str__(self):
        return "Question to " + str(self.recipient)


class WishingWell(models.Model):
    name=models.CharField(max_length=20)
    crush_desc=models.TextField(max_length=1500)

    def __str__(self):
        return str(self.name)+" 's crush description"


class Sorry(models.Model):
    name=models.CharField(max_length=20)
    sorry=models.TextField(max_length=1000)
    to=models.CharField(max_length=20)

    def __str__(self):
        return str(self.name)+ " 's sorry to " + str(self.to)

party/views.py
from django.shortcuts import render
from .models import Feedback,Gotcha,Oqp,Sorry,WishingWell
# Create your views here.


def index(request):
    if request.method=="GET":
        return render(request,'index.html',{'all_feedbacks':Feedback.objects.all()})

    if request.method=="POST":
        name=request.POST.get('feedback_name',None)
        feedback=request.POST.get('feedback',None)
        feedback_instance=Feedback.objects.create(name=name,feedback=feedback)

        context={'your_feedback':feedback_instance,
                 'all_feedbacks':Feedback.objects.all()}
        return render(request,'index.html',context)


def gotcha(request):
    if request.method=="GET":
        return render(request,'gotcha.html',{'all_gotchas':Gotcha.objects.all()})

    if request.method=="POST":
        secret=request.POST.get('secret',None)
        gotcha_instance=Gotcha.objects.create(secret=secret)
        gotcha_instance.save()
        context={'your_gotcha':gotcha_instance,
                 'all_gotchas':Gotcha.objects.all(),}
        return render(request,'gotcha.html',context)



def oqp(request):
    if request.method=="GET":
        return render(request, 'oqp.html', {'oqps': Oqp.objects.all()})

    if request.method=="POST":
        recipient=request.POST.get('questo',None)
        question=request.POST.get('onequestion',None)
        oqp_instance=Oqp.objects.create(recipient=recipient,question=question)

        context={
            'your_question':oqp_instance,
            'oqps':Oqp.objects.all()
        }

        return render(request,'oqp.html',context)



def wishingwell(request):
    if request.method=="GET":
        return render(request, 'wishwell.html', {'wishes': WishingWell.objects.all()})

    if request.method=="POST":
        name=request.POST.get('wisher_name',None)
        crush_desc=request.POST.get('crush_desc',None)
        ww_instance=WishingWell.objects.create(name=name,crush_desc=crush_desc)

        context={
            'your_wish':ww_instance,
            'wishes':WishingWell.objects.all()
        }
        return render(request,'wishwell.html',context)



def sorry(request):
    if request.method=="GET":
        return render(request, 'sorry.html', {'sorries': Sorry.objects.all()})

    if request.method=="POST":
        name=request.POST.get('sorry_from',None)
        sorry_desc=request.POST.get('sorry_desc',None)
        to=request.POST.get('sorry_to',None)

        sorry_instance=Sorry.objects.create(name=name,sorry=sorry_desc,to=to)

        context={
            'your_sorry':sorry_instance,
            'sorries':Sorry.objects.all(),
        }
        return render(request,'sorry.html',context)

templates/gotcha.html
{% extends 'index.html' %}

{% block content %}
    <div class="text-center jumbotron" style="background-color:#ffe57f  ;margin-bottom: 0;">
    <h2>Gotcha </h2>
    <br/>
    <h5>Write a secret you know about anyone in the hall and leave the rest to us  ;) </h5>

<br/>
    <div class="text-center card-deck" style="background: space;">
        {% for gotcha in all_gotchas %}
        <div class="card animated lightSpeedIn">
  <div class="card-body">
    <h4 class="card-title"># {{ gotcha.sl_no }}</h4>
    <p class="card-text">{{ gotcha.secret}}</p>

  </div>
</div>
{% endfor %}

    </div>
<br/>


    <!--modal-->
    <!-- Button to Open the Modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#gotchamodal">
  Psst! Do You Have A Secret Too?
</button>

<!-- The Modal -->
<div class="modal" id="gotchamodal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Tell us the secret you know!</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <div>
              {% if not your_gotcha %}
    <form method="post">
        {% csrf_token %}


          <div class="form-group">
            <label for="cd">Secret:</label>
              <textarea name="secret" id="cd" PLACEHOLDER="Text here..." class="form-control"></textarea>
        </div>

    <button class="btn btn-info" type="submit">Submit</button>
    </form>
    {% endif %}
        </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>
    <!--modal-->






</div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Farewell</title>
 <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

<link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.css" rel="stylesheet">

  <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">

    <style>
        .nav-item{
            margin-right: 10px;

        }
        .white-text{
            color: white;
        }
        .white-text:hover{
            color: navajowhite;
        }

        .navbar-toggler{
            background-color: #c0ca33;
        }
        .navbar-toggler-icon{
            background-color: #827717;
            border-radius: 50px;
            border-width: 5px;
            border-color: #eeff41;
            border-style: solid;
            animation-duration: 3s !important;
        }

        .card{
            box-shadow: 7px 7px 7px grey;
        }

            h2{
                color:darkred;
                text-shadow: 3px 3px 3px yellowgreen;
                font-family: 'Orbitron', sans-serif;
            }


    </style>




    </head>



<body id="top">
<div class="jumbotron text-center" style="background-color: #f4ff81;margin-bottom: 0;">
    <h1 class="display-2">Farewell</h1>
</div>


<!--navbar-->

 <nav class="navbar navbar-expand-md" style="background-color: #827717; ">
  <!-- Brand -->
  <a class="navbar-brand white-text" href="{% url 'party:index' %}">Home</a>

  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon animated flipInY "></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link  btn btn-primary" href="{% url 'party:gotcha' %}">Gotcha</a>
      </li>
      <li class="nav-item">
        <a class="nav-link  btn btn-warning" href="{% url 'party:oqp' %}">One Question Please</a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn btn-success" href="{% url 'party:ww' %}">Wishing Well</a>
      </li>
           <li class="nav-item">
        <a class="nav-link  btn btn-danger" href="{% url 'party:sorry' %}">Sorry</a>
      </li>
    </ul>
  </div>
</nav>
<!--navbar-->



<!--Thank you seniors-->

<div class="text-center jumbotron" style="background-color: #eeff41;margin-bottom: 0;">
    <h2 >Thank You Seniors</h2>
    <p>You never know how luck strikes you.Ever. But only after being hit by do you know about it.
   Such was the case with us too! How lucky could anyone be to have had seniors , who treat you like siblings,
    sooth you out of confusions, whenever you have one , shower you with priceless advices to help you walk
        a better path? And yes we are! You guys have been everything just awesome seniors, probably the best
        anyone could get. THANK YOU !!
    </p>
</div>
<!--THnak you seniors-->




<!--Game content here-->
{% block content %}


<!--FeedBack-->
<div class="text-center jumbotron" style="background-color:#fff9c4;margin-bottom: 0;">
    <h2 >Feedback Section</h2>
<br/>
    <br/>
    <!--Carousel-->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->


  <!-- The slideshow -->
  <div class="carousel-inner">
    <div class="carousel-item active">
      <h1 style="padding: 20px 20px 20px 20px;">
          -- Feedbacks --
      </h1>

    </div>
      {% for feedback in all_feedbacks %}
    <div class="carousel-item">
      <h3>
          {{ feedback.feedback }}
      </h3>
        <h6>{{ feedback.name }}</h6>
    </div>
          <br/>
          <br/>
      {% endfor %}

  </div>


  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#myCarousel" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#myCarousel" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>
    <!--CArousel-->


<!--modal-->
 <!-- Button to Open the Modal -->
<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#feedback">
  Give Feedback
</button>

<!-- The Modal -->
<div class="modal" id="feedback">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Feedback</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
         <div >
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="qto">Name:</label>
            <input type="text" name="feedback_name" id="qto" class="form-control"/>
        </div>

          <div class="form-group">
            <label for="qq">Your Question</label>
              <textarea type="text" name="feedback" id="qq" class="form-control" placeholder="Feedback here"></textarea>
        </div>

    <button class="btn btn-info" type="submit">Submit</button>
    </form>
            </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>
<!--modal-->
</div>



<!--FeedBack-->

{% endblock %}

<!--Game content here-->







<!--Footer-->
<div class="text-center jumbotron text-light" style="background-color: #424242 ;margin-bottom: 0;">
  <h3>
      <a href="#top">
      <button class="btn btn-default" type="button">^</button>
      </a>
  </h3>
    <br/>
    <br/>
    <p>Created By <code>Ganesh Sharma</code></p>

</div>
<!--Footer-->
</body>

</html>

templates/oqp.html
{% extends 'index.html' %}

{% block content %}
    <div class="text-center jumbotron" style="background-color: #b3e5fc;margin-bottom: 0;">
    <h2>One Question Please</h2>
    <br/>
    <h5>One Question Please allows you to express that lasting doubt about that weired person , you've
    had since eternity.</h5>
<br/>

    <div class="text-center card-deck" style="background: space;">
        {% for q in oqps %}
        <div class="card animated fadeIn">
  <div class="card-body">
    <h4 class="card-title text-center">{{ q.recipient }}</h4>
    <p class="card-text text-center">{{ q.question }}</p>

  </div>
</div>
{% endfor %}

    </div>
<br/>

    <!--modal-->
    <!-- Button to Open the Modal -->
<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#oqpModal">
  Do you have a question?
</button>

<!-- The Modal -->
<div class="modal" id="oqpModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Your Question</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
         <div >
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="qto">Question To?:</label>
            <input type="text" name="questo" id="qto" class="form-control"/>
        </div>

          <div class="form-group">
            <label for="qq">Your Question</label>
              <input type="text" name="onequestion" id="qq" class="form-control">
        </div>

    <button class="btn btn-primary" type="submit">Submit</button>
    </form>
            </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>
    <!--modal-->


        {% if not your_question %}

    {% endif %}




</div>
{% endblock %}

templates/sorry.html
{% extends 'index.html' %}

{% block content %}
    <div class="text-center jumbotron" style="background-color: #ccff90;margin-bottom: 0;">
    <h2>Sorry</h2>
    <br/>
    <h5>4 years , 64 subjects , 128 internals and countless chunks of memories made. In between all these,
    ,if you feel someone deserves your apology for however small a reason , Sorry is the
    platform for you.</h5>
<br/>

    <div class="text-center card-deck" style="background: space;">
        {% for sorry in sorries %}
        <div class="card animated flipInX">
  <div class="card-body">
    <h4 class="card-title text-center">{{ sorry.name }}</h4>
      <h6 class="text-center">to</h6>
      <h4 class="card-title text-center">{{ sorry.to }}</h4>
    <p class="card-text text-center">{{ sorry.sorry }}</p>

  </div>
</div>
{% endfor %}

    </div>
<br/>


    <!--modal-->
    <!-- Button to Open the Modal -->
<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#sorrymodal">
  Have An Apology To Make?
</button>

<!-- The Modal -->
<div class="modal" id="sorrymodal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Your Apology</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
       <div>
            {% if not your_sorry %}
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="sf">Your Name:</label>
            <input type="text" name="sorry_from" id="sf" class="form-control"/>
        </div>

          <div class="form-group">
            <label for="st">Apology recipient:</label>
              <input type="text" name="sorry_to" id="st" class="form-control">
        </div>

        <div class="form-group">
            <label for="s">Description</label>
            <textarea id="s" name="sorry_desc" placeholder="I am sorry..." class="form-control"></textarea>
        </div>

    <button class="btn btn-warning" type="submit">Submit</button>
    </form>
    {% endif %}
       </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>
    <!--modal-->






</div>
{% endblock %}

templates/wishwell.html
{% extends 'index.html' %}

{% block content %}
    <div class="text-center jumbotron" style="background-color:#ff8a80;margin-bottom: 0;">
    <h2>Wishing Well </h2>
    <br/>
    <h5>Have a crush on someone and too shy to express it? Ever dreamt about how your ideal partner should be?
    Try out Wishing Well to convey your romanticism.</h5>
<br/>

    <div class="text-center card-deck" style="background: space;">
        {% for wish in wishes %}
        <div class="card animated bounceIn">
  <div class="card-body">
    <h4 class="card-title text-center">{{ wish.name }}</h4>
    <p class="card-text text-center">{{ wish.crush_desc }}</p>

  </div>
</div>
{% endfor %}

    </div>
<br/>



    <!--modal-->
    <!-- Button to Open the Modal -->
<button type="button" class="btn btn-success" data-toggle="modal" data-target="#crushmodal">
 Dreamt Of Your Cinderella/Prince Charming?
</button>

<!-- The Modal -->
<div class="modal" id="crushmodal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Your Crush</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
       <div>
             {% if not your_wish %}
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="wn">Your Name:</label>
            <input type="text" name="wisher_name" id="wn" class="form-control"/>
        </div>

          <div class="form-group">
            <label for="cd">Your Dream Crush:</label>
              <textarea name="crush_desc" id="cd" PLACEHOLDER="Text here..." class="form-control"></textarea>
        </div>

    <button class="btn btn-success" type="submit">Submit</button>
    </form>
    {% endif %}
       </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>
    <!--modal-->






</div>
{% endblock %}